name: 💡 功能请求
description: 提议一项新功能
title: "feature: "
labels: ["💡 Feature Request"]
type: feature
body:
  - type: checkboxes
    attributes:
      label: 提交前请检查以下项目
      description: 确保在提交功能请求之前检查以下所有内容
      options:
        - label: 如果功能请求是一个插件皮肤，那么该插件必须已经被广泛使用，并且支持中文
          required: true
        - label: 我根本没看这些确认事项，请直接关闭我的请求
          required: false
        - label: 此功能不和现在已经存在的其他功能请求重复
          required: true
  - type: textarea
    validations:
      required: false
    attributes:
      label: 你的功能请求是否与某个问题相关？请描述一下。
      description: 清楚简洁地描述问题所在。例如：我总是因为 [...] 而感到困扰
  - type: textarea
    validations:
      required: false
    attributes:
      label: 描述你希望的解决方案
      description: 清楚简洁地描述你希望实现的功能。
  - type: textarea
    validations:
      required: false
    attributes:
      label: 描述你考虑过的替代方案，插件或是 WeakAuras
      description: 清楚简洁地描述你考虑过的任何替代解决方案或功能。
  - type: textarea
    validations:
      required: false
    attributes:
      label: 附加信息
      description: 在此添加关于功能请求的任何其他信息或截图。