name: 💡 Feature Request
description: Suggest a new feature
title: "feature: "
labels: ["💡 Feature Request"]
type: feature
body:
  - type: checkboxes
    attributes:
      label: Did you check these before submitting?
      description: Make sure you checked all of the below before submitting an feature request
      options:
        - label: If the feature request is a addon skin, the addon must be widely used and support Chinese.
          required: true
        - label: I have not read any of these steps, please close my issue when you see it.
          required: false
        - label: This feature is NOT a duplicate of an existing feature request.
          required: true
  - type: textarea
    validations:
      required: false
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    validations:
      required: false
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Describe alternatives you've considered, including addons or WeakAuras
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.