name: ✅ Issue Checker

on:
  issues:
    types: [opened]

jobs:
  check-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Check for trap steps
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || '';

            const trapPhrasesChinese = [
              '我根本没看这些确认步骤，请直接关闭我的问题',
              '我根本没看这些确认事项，请直接关闭我的请求'
            ];

            const trapPhrasesEnglish = [
              'I have not read any of these steps, please close my issue when you see it.',
            ]

            let foundTrap = false;
            let trapPhrase = '';


            for (const phrase of [...trapPhrasesChinese, ...trapPhrasesEnglish]) {
              // Look for checked checkbox pattern: - [x] phrase
              const checkedPattern = new RegExp(`- \\[x\\]\\s*${phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'i');
              if (checkedPattern.test(body)) {
                foundTrap = true;
                trapPhrase = phrase;
                break;
              }
            }

            if (foundTrap) {
              const isChinese = trapPhrasesChinese.includes(trapPhrase);
              let comment;
              if (isChinese) {
                comment = `⚠️ **此问题可能会被关闭，因为您选择了"${trapPhrase}"**\n\n此提示表明您在提交 Issue 前未阅读要求。请仔细阅读检查清单并按照指引创建新的 Issue。`;
              } else {
                comment = `⚠️ **The issue will probably be closed, because you selected "${trapPhrase}"**\n\nThis indicates that you did not read the requirements before submitting the issue. Please read the checklist carefully and create a new issue following the proper guidelines.`;
              }

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: comment
              });

              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['❌ Invalid']
              });
            }
